language: bash
services: docker

env:
  - VERSION=7.1 LINUX=alpine MODE=fpm

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$LINUX/$MODE"
  - image="php:${VERSION}-${LINUX}-${MODE}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images